@gen_test
def test_exception(self):
    yield self.client.testException('Safe')
    try:
        yield self.client.testException('Xception')
    except Xception as ex:
        self.assertEqual(ex.errorCode, 1001)
        self.assertEqual(ex.message, 'Xception')
    else:
        self.fail('should have gotten exception')
    try:
        yield self.client.testException('throw_undeclared')
    except TTransportException as ex:
        pass
    else:
        self.fail('should have gotten exception')
